name: "Zephyr Twister"
description: "Run tests with twister"
inputs:
  tags:
    required: false
    type: string
    description: "Twister tags"
  options:
    required: false
    type: string
    description: "Extra options to pass to twister"
    default: ""
  board:
    required: false
    type: string
    description: "Board to run the test on"
  path:
    required: false
    type: string
    description: "Path to the test directory"

runs:
  using: "composite"
  steps:
    - name: Run test with twister
      shell: bash
      run: |
        if [[ -n "${{ inputs.tags }}" ]]; then
          test=""
          for tag in $(echo ${{ inputs.tags }} | tr "," "\n"); do
            test="$test -t $tag"
          done
        fi
        if [[ -n "${{ inputs.board }}" ]]; then
          board="-p ${{ inputs.board }}"
        fi
        if [[ -n "${{ inputs.path }}" ]]; then
          path="-T ${{ inputs.path }}"
        fi
        west twister $test $board $path ${{ inputs.options }}
