name: 'Zephyr Twister'
description: 'Run tests with twister'
inputs:
  test:
    required: true
    type: string
    description: "Test to run"
  options:
    required: false
    type: string
    description: "Extra options to pass to twister"
    default: ""
  board:
    required: false
    type: string
    description: "Board to run the test on"

runs:
  using: "composite"
  steps:
    - name: Run test with twister
      if: ${{ inputs.board }}
      shell: bash
      run: west twister -t ${{ inputs.test }} -b ${{ inputs.board }} ${{ inputs.options }}
    - name: Run test with twister
      if: ${{ !inputs.board }}
      shell: bash
      run: west twister -t ${{ inputs.test }} ${{ inputs.options }}