name: 'Zephyr Twister'
description: 'Run tests with twister'
inputs:
  test:
    required: false
    type: string
    description: "Test to run"
  options:
    required: false
    type: string
    description: "Extra options to pass to twister"
    default: ""
  board:
    required: false
    type: string
    description: "Board to run the test on"
  path:
    required: false
    type: string
    description: "Path to the test directory"
    default: "samples"
  extra_cmd:
    required: false
    type: string
    description: "Extra command to run before build"
    default: "echo ''"

runs:
  using: "composite"
  steps:
    - name: Run Extra Command
      shell: bash
      run: ${{ inputs.extra_cmd }}

    - name: Run test with twister
      shell: bash
      run: |
        if [[ -n "${{ inputs.path }}" ]]; then
          test = -t  ${{ inputs.test }}
        fi
        if [[ -n "${{ inputs.board }}" ]]; then
          board = -b ${{ inputs.board }}
        fi
        west twister $test $board -T ${{ inputs.path }} ${{ inputs.options }}
