name: 'Zephyr Init'
description: 'Initialize Zephyr workspace'
inputs:
  personal_access_token:
    required: true
  manifest_path:
    description: "Path to the manifest file"
    required: false
    default: "workdir"

runs:
  using: "composite"
  steps:
    - name: Setup permission
      shell: bash
      run: |
        git config --global credential.helper store
        echo "https://$GITHUB_ACTOR:${{ inputs.personal_access_token }}@github.com" >~/.git-credentials

    - name: Init and Update Zephyr Application
      shell: bash
      run: |
        cd /6tron-workspace/
        rm -rf .west
        west init -l ${{ inputs.manifest_path }}
        west update
