name: 'Zephyr Build'
description: 'Build the Zephyr project'
inputs:
  application:
    required: true
    type: string
  board:
    required: false
    type: string
  personal_access_token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup permission
      shell: bash
      run: |
        git config --global credential.helper store
        echo "https://$GITHUB_ACTOR:${{ inputs.personal_access_token }}@github.com" >~/.git-credentials
    - name: Init and Update Zephyr Application
      shell: bash
      run: |
        rm -rf .west
        west init -l workdir
        west update
    - name: Build Zephyr Application
      shell: bash
      if: ${{ inputs.board }}
      run: west build -b ${{ inputs.board }} workdir/${{ inputs.application }} -p
    - name: Build Zephyr Application
      shell: bash
      if: ${{ !inputs.board }}
      run: west build workdir/${{ inputs.application }} -p
