name: 'Zephyr Build'
description: 'Build the Zephyr project'
inputs:
  application:
    required: true
    type: string
  board:
    required: false
    type: string
    default: ""
  shield:
    required: false
    type: string
    default: ""
  extra_args:
    required: false
    type: string
    default: ""
  overlay:
    required: false
    type: string
    default: ""

runs:
  using: "composite"
  steps:
    - name: Overwrite Overlay
      shell: bash
      if: ${{ inputs.overlay != '' }}
      run: echo "${{ inputs.overlay }}" > "${{ inputs.application }}/app.overlay"

    - name: Build Zephyr Application
      shell: bash
      if: ${{ inputs.board != '' && inputs.shield != '' }}
      run: west build -b ${{ inputs.board }} --shield ${{ inputs.shield }} ${{ inputs.application }} -p ${{ inputs.extra_args }}

    - name: Build Zephyr Application
      shell: bash
      if: ${{ inputs.board != '' &&  inputs.shield == '' }}
      run: west build -b ${{ inputs.board }} ${{ inputs.application }} -p ${{ inputs.extra_args }}

    - name: Build Zephyr Application
      shell: bash
      if: ${{ inputs.board == '' && inputs.shield != '' }}
      run: west build --shield ${{ inputs.shield }} ${{ inputs.application }} -p ${{ inputs.extra_args }}

    - name: Build Zephyr Application
      shell: bash
      if: ${{ inputs.board == '' && inputs.shield == '' }}
      run: west build ${{ inputs.application }} -p ${{ inputs.extra_args }}

    - name: Remove Overlay
      shell: bash
      if: ${{ inputs.overlay != '' }}
      run: rm "${{ inputs.application }}/app.overlay"
