name: 'Zephyr Build'
description: 'Build the Zephyr project'
inputs:
  application:
    required: true
    type: string
  board:
    required: false
    type: string
    default: ""
  shield:
    required: false
    type: string
    default: ""

runs:
  using: "composite"
  steps:
    - name: Build Zephyr Application
      shell: bash
      if: ${{ inputs.board != '' && inputs.shield != '' }}
      run: west build -b ${{ inputs.board }} --shield ${{ inputs.shield }} ${{ inputs.application }} -p

    - name: Build Zephyr Application
      shell: bash
      if: ${{ inputs.board != '' &&  inputs.shield == '' }}
      run: west build -b ${{ inputs.board }} ${{ inputs.application }} -p

    - name: Build Zephyr Application
      shell: bash
      if: ${{ inputs.board == '' && inputs.shield != '' }}
      run: west build --shield ${{ inputs.shield }} ${{ inputs.application }} -p

    - name: Build Zephyr Application
      shell: bash
      if: ${{ inputs.board == '' && inputs.shield == '' }}
      run: west build ${{ inputs.application }} -p
