name: Generate Zephyr Manifest
description: Generates the west.yml file
inputs:
  sixtron_revision:
    description: "6TRON Manifest revision"
    required: false
  sixtron_module_allowlist:
    description: "6TRON Module allowlist"
    required: false
  zephyr_revision:
    description: "Zephyr revision"
    required: false
  repository_revision:
    description: "Repository revision"
    required: true
  repo_board:
    description: "Board repository"
    required: false
  sixtron_connector_revision:
    description: "sixtron-connector revision"
    required: false
  manifest_path:
    description: "Path to the manifest file"
    required: false
    default: "workdir"

runs:
  using: "composite"
  steps:
    - name: Create manifest directory
      shell: bash
      run: |
        mkdir -p ${{ inputs.manifest_path }}

    - name: Add remotes to YAML file
      shell: bash
      run: |
        echo "manifest:" > ${{ inputs.manifest_path }}/west.yml
        echo "  remotes:" >> ${{ inputs.manifest_path }}/west.yml
        echo "    - name: zephyrproject-rtos" >> ${{ inputs.manifest_path }}/west.yml
        echo "      url-base: https://github.com/zephyrproject-rtos" >> ${{ inputs.manifest_path }}/west.yml
        echo "    - name: catie-6tron" >> ${{ inputs.manifest_path }}/west.yml
        echo "      url-base: https://github.com/catie-aq" >> ${{ inputs.manifest_path }}/west.yml

    - name: Add Zephyr to YAML file
      shell: bash
      run: |
        cat << EOF >> ${{ inputs.manifest_path }}/west.yml
          projects:
            - name: zephyr
              remote: zephyrproject-rtos
              revision: ${{ inputs.zephyr_revision }}
              import:
                name-blocklist:
                  - hal_altera
                  - hal_ambiq
                  - hal_atmel
                  - hal_espressif
                  - hal_ethos_u
                  - hal_gigadevice
                  - hal_infineon
                  - hal_intel
                  - hal_microchip
                  - hal_nuvoton
                  - hal_nxp
                  - hal_openisa
                  - hal_quicklogic
                  - hal_renesas
                  - hal_rpi_pico
                  - hal_silabs
                  - hal_st
                  - hal_telink
                  - hal_ti
                  - hal_wurthelektronik
                  - hal_xtensa
        EOF

    - name: Append modules to YAML file
      if: ${{ inputs.repository_revision }}
      shell: bash
      run: |
        cat << EOF >> ${{ inputs.manifest_path }}/west.yml
            - name: ${{ github.event.repository.name }}
              remote: catie-6tron
              revision: ${{ inputs.repository_revision }}
        EOF

    - name: Append 6TRON Manifest to YAML file
      if: ${{ inputs.sixtron_revision != '' && inputs.sixtron_module_allowlist == '' }}
      shell: bash
      run: |
        cat << EOF >> ${{ inputs.manifest_path }}/west.yml
            - name: 6tron-manifest
              remote: catie-6tron
              repo-path: zephyr_6tron-manifest
              revision: ${{ inputs.sixtron_revision }}
              path: 6tron/6tron-manifest
              import: true
        EOF

    - name: Append 6TRON Module allowlist to YAML file
      if: ${{ inputs.sixtron_revision != '' && inputs.sixtron_module_allowlist != '' }}
      shell: bash
      run: |
        allowlist=""
        for module in $(echo ${{ inputs.sixtron_module_allowlist }} | tr "," "\n"); do
          allowlist="$allowlist          - $module"$'\n'
        done
        cat << EOF >> ${{ inputs.manifest_path }}/west.yml
            - name: 6tron-manifest
              remote: catie-6tron
              repo-path: zephyr_6tron-manifest
              revision: ${{ inputs.sixtron_revision }}
              path: 6tron/6tron-manifest
              import:
                name-allowlist:
        $allowlist
        EOF

    - name: Append sixtron-connector to YAML file
      if: ${{ inputs.sixtron_connector_revision }}
      shell: bash
      run: |
        cat << EOF >> ${{ inputs.manifest_path }}/west.yml
            - name: 6tron_manifest
              remote: catie-6tron
              repo-path: zephyr_6tron-manifest
              revision: ${{ inputs.sixtron_connector_revision }}
              path: 6tron/6tron_manifest
              import:
                name-allowlist:
                  - 6tron_connector
        EOF

    - name: cat west.yml
      shell: bash
      run: cat ${{ inputs.manifest_path }}/west.yml
