name: 'Generate Zephyr Manifest'
description: 'Generates the west.yml file'
inputs:
  sixtron_revision:
    required: true
    type: string
  repository_revision:
    required: true
    type: string
  repo_board:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Create workdir/west.yml
      shell: bash
      run: |
        mkdir -p workdir
        touch workdir/west.yml

    - name: Get version without suffix
      shell: bash
      id: get-version
      run: |
        VERSION=${{ inputs.sixtron_revision }}
        VERSION_WITHOUT_SUFFIX=$(echo $VERSION | cut -d'+' -f1)
        echo "version=$VERSION_WITHOUT_SUFFIX" >> $GITHUB_OUTPUT

    - name: Replace underscores with hyphens
      id: replace-characters
      shell: bash
      run: |
        REPO_BOARD=${{ inputs.repo_board }}
        REPO_BOARD_WITH_HYPHENS=$(echo $REPO_BOARD | tr '_' '-')
        echo "repo_board=$REPO_BOARD_WITH_HYPHENS" >> $GITHUB_OUTPUT
    
    - name: Generate YAML file
      shell: bash
      run: |
        cat << EOF > workdir/west.yml
        manifest:
          remotes:
            - name: zephyrproject-rtos
              url-base: https://github.com/zephyrproject-rtos
            - name: catie-6tron
              url-base: https://github.com/catie-aq
          projects:
            - name: zephyr
              remote: zephyrproject-rtos
              revision: ${{ steps.get-version.outputs.version }}
              import: true
            - name: ${{ github.event.repository.name }}
              remote: catie-6tron
              revision: ${{ inputs.repository_revision }}
            - name: 6tron-manifest
              remote: catie-6tron
              repo-path: zephyr_6tron-manifest
              revision: ${{ inputs.sixtron_revision }}
              path: 6tron/6tron-manifest
              import: 
                name-allowlist:
                  - 6tron-connector
                  - ${{ steps.replace-characters.outputs.repo_board }}
        EOF
