name: 'Generate Zephyr Manifest'
description: 'Generates the west.yml file'
inputs:
  zephyr_revision:
    required: true
    type: string
  6tron_revision:
    required: true
    type: string
  repository_revision:
    required: true
    type: string
  repo_board:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Create workdir/west.yml
      shell: bash
      run: |
        mkdir -p workdir
        touch workdir/west.yml
    - name: Generate YAML file
      shell: bash
      run: |
        cat << EOF > workdir/west.yml
        manifest:
          remotes:
            - name: zephyrproject-rtos
              url-base: https://github.com/zephyrproject-rtos
            - name: catie-6tron
              url-base: https://github.com/catie-aq
          projects:
            - name: zephyr
              remote: zephyrproject-rtos
              revision: ${{ inputs.zephyr_revision }}
              import: true
            - name: ${{ github.event.repository.name }}
              remote: catie-6tron
              revision: ${{ inputs.repository_revision }}
            - name: 6tron-manifest
              remote: catie-6tron
              repo-path: zephyr_6tron-manifest
              revision: ${{ inputs.6tron_revision }}
              path: 6tron/6tron-manifest
              import: 
                name-allowlist:
                  - 6tron-connector
                  - ${{ inputs.repo_board }}
        EOF
