name: Generate Zephyr Manifest
description: Generates the west.yml file
inputs:
  sixtron_revision:
    description: "6TRON Manifest revision"
    required: true
  zephyr_revision:
    description: "Zephyr revision"
    required: false
  repository_revision:
    description: "Repository revision"
    required: true
  repo_board:
    description: "Board repository"
    required: false
runs:
  using: "composite"
  steps:
    - name: Create workdir/west.yml
      shell: bash
      run: |
        mkdir -p workdir
        touch workdir/west.yml

    - name: Get Zephyr Version without suffix
      shell: bash
      id: get-version
      run: |
        if [ "${{ inputs.zephyr_revision }}" != "" ]; then
          VERSION=${{ inputs.zephyr_revision }}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          VERSION=${{ inputs.sixtron_revision }}
          VERSION_WITHOUT_SUFFIX=$(echo $VERSION | cut -d'+' -f1)
          echo "version=$VERSION_WITHOUT_SUFFIX" >> $GITHUB_OUTPUT
        fi

    - name: Replace underscores with hyphens
      id: replace-characters
      shell: bash
      run: |
        if [ "${{ inputs.repo_board }}" != "" ]; then
          REPO_BOARD=${{ inputs.repo_board }}
          REPO_BOARD_WITH_HYPHENS=$(echo $REPO_BOARD | tr '_' '-')
          REPO_BOARD_WITH_HYPHENS_LIST="- ${REPO_BOARD_WITH_HYPHENS}"
          echo "repo_board=$REPO_BOARD_WITH_HYPHENS_LIST" >> $GITHUB_OUTPUT
        else
          echo "repo_board=" >> $GITHUB_OUTPUT
        fi

    - name: Generate YAML file
      shell: bash
      run: |
        cat << EOF > workdir/west.yml
        manifest:
          remotes:
            - name: zephyrproject-rtos
              url-base: https://github.com/zephyrproject-rtos
            - name: catie-6tron
              url-base: https://github.com/catie-aq
          projects:
            - name: zephyr
              remote: zephyrproject-rtos
              revision: ${{ steps.get-version.outputs.version }}
              import:
                name-blocklist:
                  - hal_altera
                  - hal_ambiq
                  - hal_atmel
                  - hal_espressif
                  - hal_ethos_u
                  - hal_gigadevice
                  - hal_infineon
                  - hal_intel
                  - hal_microchip
                  - hal_nuvoton
                  - hal_nxp
                  - hal_openisa
                  - hal_quicklogic
                  - hal_renesas
                  - hal_rpi_pico
                  - hal_silabs
                  - hal_st
                  - hal_telink
                  - hal_ti
                  - hal_wurthelektronik
                  - hal_xtensa
            - name: ${{ github.event.repository.name }}
              remote: catie-6tron
              revision: ${{ inputs.repository_revision }}
            - name: 6tron-manifest
              remote: catie-6tron
              repo-path: zephyr_6tron-manifest
              revision: ${{ inputs.sixtron_revision }}
              path: 6tron/6tron-manifest
              import:
                name-allowlist:
                  - 6tron-connector
                  ${{ steps.replace-characters.outputs.repo_board }}
        EOF
