# action.yaml
name: 'Update Zephyr Manifest'
description: 'Update Zephyr manifest with the latest module SHA'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Perform Update
      id: update
      run: python update_manifest/update.py
      shell: bash