# action.yaml
name: "Update Zephyr Manifest"
description: "Update Zephyr manifest with the latest module SHA"

inputs:
  manifest:
    description: "Path to the manifest file"
    required: true
  personal_access_token:
    description: "Personal Access Token for GitHub"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      run: |
        cd ${GITHUB_ACTION_PATH}
        pip install poetry
        poetry install
      shell: bash
    - name: Perform Update
      id: update
      run: | 
        cd ${GITHUB_ACTION_PATH}
        poetry run update --manifest ${{ inputs.manifest }} --token ${{ inputs.personal_access_token }}
        echo "::set-output name=change::${GITHUB_ACTION_PATH}/change.md"
        echo "::set-output name=matrix::${GITHUB_ACTION_PATH}/matrix.json"
      shell: bash
    - name: Upload change.md in cache
      uses: actions/upload-artifact@v4
      with:
        name: change
        path: ${{ steps.update.outputs.change }}
    - name: Upload matrix.json in cache
      uses: actions/upload-artifact@v4
      with:
        name: matrix
        path: ${{ steps.update.outputs.matrix }}
    - name: Clean up
      if: always()
      run: |
        rm -rf ${GITHUB_ACTION_PATH}
      shell: bash
