# action.yaml
name: "Update Zephyr Manifest"
description: "Update Zephyr manifest with the latest module SHA"

inputs:
  manifest:
    description: "Path to the manifest file"
    required: true
  personal_access_token:
    description: "Personal Access Token for GitHub"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      run: |
        cd ${GITHUB_ACTION_PATH}
        pip install poetry
        poetry install
      shell: bash
    - name: Perform Update
      id: update
      run: | 
        cd ${GITHUB_ACTION_PATH}
        poetry run update --manifest ${{ inputs.manifest }} --token ${{ inputs.personal_access_token }}
        echo "::set-output name=change::${GITHUB_ACTION_PATH}/change.md"
        echo "::set-output name=matrix::${GITHUB_ACTION_PATH}/matrix.json"
        echo "::set-output name=matrix_core::${GITHUB_ACTION_PATH}/matrix_core.json"
        echo "::set-output name=west::${GITHUB_ACTION_PATH}/test_manifest.yml"
      shell: bash
    - name: Upload change.md in cache
      uses: actions/upload-artifact@v4
      with:
        name: change
        path: ${{ steps.update.outputs.change }}
    - name: Upload matrix.json in cache
      uses: actions/upload-artifact@v4
      with:
        name: matrix
        path: ${{ steps.update.outputs.matrix }}
    - name: Upload test_manifest.yml in cache
      uses: actions/upload-artifact@v4
      with:
        name: west
        path: ${{ steps.update.outputs.west }}
    - name: Upload matrix_core.json in cache
      uses: actions/upload-artifact@v4
      with:
        name: matrix_core
        path: ${{ steps.update.outputs.matrix_core }}
    - name: Clean up
      if: always()
      run: |
        rm -rf ${GITHUB_ACTION_PATH}
      shell: bash
