# action.yaml
name: "Update Zephyr Manifest"
description: "Update Zephyr manifest with the latest module SHA"

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        cd ${{github.action_path}}
        pip install poetry
        poetry install
      shell: bash
    - name: Perform Update
      id: update
      run: poetry run update
      shell: bash
