# action.yaml
name: "Update Zephyr Manifest"
description: "Update Zephyr manifest with the latest module SHA"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      run: |
        cd ${GITHUB_ACTION_PATH}
        pip install poetry
        poetry install
      shell: bash
    - name: Perform Update
      id: update
      run: | 
        cd ${GITHUB_ACTION_PATH}
        poetry shell
        update
      shell: bash
