name: Build & Test Zephyr Application

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      board:
        required: false
        type: string
      container:
        required: false
        type: string
        default: "zephyrprojectrtos/ci"
      extra_cmd:
        required: false
        type: string
        description: "Extra command to run before build"
        default: ""
    secrets:
      personal_access_token:
        required: true


permissions: read-all

jobs:
  pre-commit:
    uses: catie-aq/generic_workflows/.github/workflows/pre-commit.yaml@main
  build:
    runs-on: self-hosted
    container:
      image: ${{ inputs.container }}
      options: --user root --privileged
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - uses: catie-aq/zephyr_workflows/zephyr-build@main

