name: Build & Test Zephyr Application

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      blobs:
        required: false
        type: string
      board:
        required: false
        type: string
      container:
        required: false
        type: string
        default: "zephyrprojectrtos/ci"
      pem_key_path:
        required: false
        type: string
      extra_cmd:
        required: false
        type: string
        description: "Extra command to run before build"
        default: ""
    secrets:
      personal_access_token:
        required: true
      pem_key:
        required: false

permissions: read-all

jobs:
  pre-commit:
    uses: catie-aq/generic_workflows/.github/workflows/pre-commit.yaml@main
  build:
    runs-on: sonu-github-arc
    container:
      image: ${{ inputs.container }}
      options: --user root --privileged
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Extra command
        if: ${{ inputs.extra_cmd }}
        run: ${{ inputs.extra_cmd }}

      - name: Copy key
        if: ${{ inputs.pem_key_path }}
        run: |
          echo "${{ secrets.pem_key }}" > ${{ inputs.pem_key_path }}

      - uses: actions/checkout@v4
        with:
          path: workdir

      - name: Copy key
        if: ${{ inputs.pem_key_path }}
        run: |
          echo "${{ secrets.pem_key }}" > workdir/${{ inputs.pem_key_path }}

      - name: replace
        if: ${{ inputs.pem_key_path }}
        run: |
            sed -i "s|CONFIG_MCUBOOT_SIGNATURE_KEY_FILE=.*|CONFIG_MCUBOOT_SIGNATURE_KEY_FILE=\"workdir/${{ inputs.pem_key_path }}\"|g" workdir/${{ inputs.application }}/prj.conf

      - uses: catie-aq/zephyr_workflows/zephyr_init@main
        with:
          personal_access_token: ${{ secrets.personal_access_token }}

      - name: Download blobs
        if: ${{ inputs.blobs }}
        run: |
          west blobs fetch ${{ inputs.blobs }}

      - uses: catie-aq/zephyr_workflows/zephyr_build@main
        with:
          application: workdir/${{ inputs.application }}
          board: ${{ inputs.board }}
