name: Build & Test Zephyr Application

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      board:
        required: false
        type: string
      container:
        required: false
        type: string
        default: "zephyrprojectrtos/ci"
      extra_cmd:
        required: false
        type: string
        description: "Extra command to run before build"
        default: ""
    secrets:
      personal_access_token:
        required: true


permissions: read-all

jobs:
  pre-commit:
    uses: catie-aq/generic_workflows/.github/workflows/pre-commit.yaml@main
  build:
    runs-on:
      group: default
    container:
      image: ${{ inputs.container }}
      options: --user root --privileged
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Extra command
        if: ${{ inputs.extra_cmd }}
        run: ${{ inputs.extra_cmd }}
      - uses: actions/checkout@v4
        with:
          path: workdir
      - uses: catie-aq/zephyr_workflows/zephyr_build@main
        with:
          application: workdir/${{ inputs.application }}
          board: ${{ inputs.board }}
          personal_access_token: ${{ secrets.personal_access_token }}
      - name: Clean up
        if: always()
        run: |
          rm -rf workdir
          rm -rf .west
          rm -rf ${{ github.workspace }}

