name: Test Zephyr Board

on:
  workflow_call:
    inputs:
      board:
        required: true
        type: string
      extra_cmd:
        required: false
        type: string
        description: "Extra command to run before build"
        default: "echo ''"
    secrets:
      personal_access_token:
        required: true

permissions: read-all

jobs:
  pre-commit:
    uses: catie-aq/generic_workflows/.github/workflows/pre-commit.yaml@main
  twister-test:
    runs-on: sonu-github-arc
    container:
      image: "zephyrprojectrtos/ci:v0.26.13"
      options: --user root --privileged
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      ZEPHYR_VERSION: "v3.7.0"
      TWISTER_OPTIONS: "--force-color --inline-logs -v --clobber-output --integration "
    steps:
      - name: Run Extra Command
        shell: bash
        run: ${{ inputs.extra_cmd }}

      - name: Get current branch name
        id: branch-names
        uses: tj-actions/branch-names@v8

      - uses: catie-aq/zephyr_workflows/generate_manifest@main
        with:
          zephyr_revision: ${{ env.ZEPHYR_VERSION }}
          repository_revision: ${{ steps.branch-names.outputs.current_branch }}
          sixtron_connector_revision: "main"

      - uses: catie-aq/zephyr_workflows/zephyr_init@main
        with:
          personal_access_token: ${{ secrets.personal_access_token }}

      - uses: catie-aq/zephyr_workflows/zephyr_twister@main
        with:
          board: ${{ inputs.board }}
          options: ${{ env.TWISTER_OPTIONS }}

      - name: Clean up
        if: always()
        run: |
          rm -rf workdir
          rm -rf .west
          rm -rf ${{ github.workspace }}
