name: Test Zephyr Shield

on:
  workflow_call:
    inputs:
      shield:
        required: true
        type: string
      container:
        required: false
        type: string
        default: "ghcr.io/catie-aq/zephyr_docker:v4.0.0-202502-ci"
      extra_cmd:
        required: false
        type: string
        description: "Extra command to run before build"
        default: "echo ''"
      dependencies:
        required: false
        type: string
        default: ""
    secrets:
      personal_access_token:
        required: true

permissions: read-all

jobs:
  pre-commit:
    uses: catie-aq/generic_workflows/.github/workflows/pre-commit.yaml@main
  build:
    runs-on: sonu-github-arc
    container:
      image: ${{ inputs.container }}
      options: --user root --privileged
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      ZEPHYR_VERSION: "v4.1.0"
    steps:
      - name: Run Extra Command
        shell: bash
        run: ${{ inputs.extra_cmd }}

      - name: Get current branch name
        id: branch-names
        uses: tj-actions/branch-names@v8

      - name: Create workdir/west.yml
        shell: bash
        run: |
          mkdir -p workdir
          touch workdir/west.yml

      - name: Generate YAML file
        shell: bash
        run: |
          cat << EOF > workdir/west.yml
          manifest:
            remotes:
              - name: zephyrproject-rtos
                url-base: https://github.com/zephyrproject-rtos
              - name: catie-6tron
                url-base: https://github.com/catie-aq
            projects:
              - name: zephyr
                remote: zephyrproject-rtos
                revision: ${{ env.ZEPHYR_VERSION }}
                import:
                  name-allowlist:
                    - cmsis
                    - hal_stm32
              - name: zephyr_zest-core-stm32l4a6rg
                remote: catie-6tron
                revision: main
              - name: zephyr_6tron-connector
                remote: catie-6tron
                revision: main
              - name: ${{ github.event.repository.name }}
                remote: catie-6tron
                revision: ${{ steps.branch-names.outputs.current_branch }}
          EOF

      - name: Add dependencies to YAML file
        shell: bash
        run: |
          if [ -n "${{ inputs.dependencies }}" ]; then
            IFS=',' read -ra dependencies <<< "${{ inputs.dependencies }}"
            for dependency in "${dependencies[@]}"; do
              echo "  - name: $dependency" >> workdir/west.yml
              echo "    remote: catie-6tron" >> workdir/west.yml
              echo "    revision: main" >> workdir/west.yml
            done
          fi

      - uses: catie-aq/zephyr_workflows/zephyr_init@main
        with:
          personal_access_token: ${{ secrets.personal_access_token }}

      - name: Transform Shield for Overlay
        id: transform-shield
        run: |
          shield="${{ inputs.shield }}"
          transformed_shield=$(echo "$shield" | tr '[:lower:]-' '[:upper:]_')
          echo "transformed_shield=$transformed_shield" >> $GITHUB_ENV

      - uses: catie-aq/zephyr_workflows/zephyr_build@main
        with:
          board: zest_core_stm32l4a6rg
          application: zephyr/samples/basic/blinky
          shield: ${{ inputs.shield }}
          overlay: "${{ env.transformed_shield }}(1)"
