name: Test Zephyr Shield

on:
  workflow_call:
    inputs:
      shield:
        required: true
        type: string
      container:
        required: false
        type: string
        default: "ghcr.io/catie-aq/zephyr_docker:v0.27.4-workspace"
      extra_cmd:
        required: false
        type: string
        description: "Extra command to run before build"
        default: "echo ''"
    secrets:
      personal_access_token:
        required: true

permissions: read-all

jobs:
  pre-commit:
    uses: catie-aq/generic_workflows/.github/workflows/pre-commit.yaml@main
  build:
    runs-on: sonu-github-arc
    container: ${{ inputs.container }}
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      ZEPHYR_VERSION: "v4.0.0"
    steps:
      - name: Run Extra Command
        shell: bash
        run: ${{ inputs.extra_cmd }}

      - name: Get current branch name
        id: branch-names
        uses: tj-actions/branch-names@v8

      - uses: catie-aq/zephyr_workflows/generate_manifest@49-use-image-including-6tron-workspace
        with:
          sixtron_revision: "main"
          zephyr_revision: ${{ env.ZEPHYR_VERSION }}
          sixtron_module_allowlist: "6tron_connector,zest_core_fmlr-72,zest_core_nrf52832,zest_core_nrf5340,zest_core_stm32g474ve,zest_core_stm32h753zi,zest_core_stm32l4a6rg,zest_core_stm32l562ve"
          repository_revision: ${{ steps.branch-names.outputs.current_branch }}
          manifest_path: 6tron-project

      - uses: catie-aq/zephyr_workflows/zephyr_init@49-use-image-including-6tron-workspace
        with:
          personal_access_token: ${{ secrets.personal_access_token }}
          manifest_path: 6tron-project

      - uses: catie-aq/zephyr_workflows/zephyr_build@main
        with:
          board: zest_core_stm32l4a6rg
          application: zephyr/samples/basic/blinky
          shield: ${{ inputs.shield }}
